# Generated by Django 4.2.27 on 2026-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0003_alter_fishingplace_map_embed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='methods/'),
        ),
    ]
