# Generated by Django 4.2.27 on 2026-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0004_method_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fishingplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
    ]
